/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package newReport5;

public class App {
    public static void main(String[] args) {
        String str = "百二十三";

        
        int value = Integer.parseInt(str);

    }
}
